### ISSUE TITLE
Trying to use shared_guarded.hpp  with C++17

### ISSUE THREAD

**Issue by jogster** [copperspice/libguarded#11]
The file has a HAVE_CXX14 define required - can this be updated otherwise I get incomplete type warnings.

I ended up just editing the file and changing the #if to #ifndef

**Comment by jogster** [comment]
Finally ended up defining HAVE_CXX14 in my project - wouldn't a compiler check be better?

**Comment by agserm** [comment]
Yes, the right way to handle this is to define HAVE_CXX14 in your project if you have C++14 features in your toolchain. The next release of libGuarded will add CMake build files which should automatically handle this for dependent projects.

Unfortunately, there is no feature test macro for the shared_mutex features, and checking for a compiler would not help since C++14 can be enabled or disabled without changing compilers.
